[package]
name = "bpa_rs"
version = "0.1.0"
edition = "2024"
description = "A Rust implementation of the Binary Partitioning Algorithm (BPA) for 3D point cloud data."
license = "MIT"
authors = ["Martin Frances<martinfrances107@hotmail.com>"]
[dependencies]
glm = "0.2.3"
